language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - hhvm

before_script:
  - phpenv config-rm xdebug.ini
  - composer install

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover coverage/clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
