language: php

php:
  - '7.1'
  - '7.2'

addons:
  mariadb: '10.3'

before_script:
  - phpenv config-rm xdebug.ini
  - cp .env.travis .env.testing
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover coverage/clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
